server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    password: admin
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
